### ISSUE TITLE
Refreshing when in game makes you a spectator 

### ISSUE THREAD

**Issue by Haroldthe24th** [Tempate/litaxx#2] opened 2020-09-29 11:29 UTC

**Comment by usr25** [comment] 2020-09-30 09:29
We could fix this using either usernames or cookies

**Comment by Haroldthe24th** [comment] 2020-09-30 11:37
@usr25 cookies sound fine, but wdym usernames?

**Comment by tempate** [comment] 2020-09-30 12:58
The issue is that right now we're identifying users by their socket's id, which apparently changes when you refresh the page. It could be fixed by giving a token to each user.

**Comment by Haroldthe24th** [comment] 2020-09-30 13:31
can you not do it based on IP?
@Tempate

**Comment by tempate** [comment] 2020-10-03 08:23
I guess it could be done, but it's non-standard. The right way is to simply set a token on the session cookies.

**Comment by tempate** [comment] 2020-10-04 07:35
It's been fixed.

**Closed as completed by tempate** 2020-10-04 07:35 UTC
Labels: bug
